### PR TITLE
maps color format from HEIF to Qt (i.e. RGB88)

### PR DESCRIPTION
**Pull request by diemmarkus**
- this patch is needed to load RGB888 heif images with libheif 1.7.0
- maps heif_chroma_interleaved_RGB to QImage::Format_RGB888
- other conversions are not added because I don't have test images

### CODE REVIEW

**Comment by diemmarkus** [comment]
having compiled [libheif v1.7.0](https://github.com/strukturag/libheif/releases/tag/v1.7.0) I could not load [C001.heic](https://github.com/nokiatech/heif_conformance/blob/master/conformance_files/C001.heic) anymore.

**Comment by ZaWertun** [comment]
>     * other conversions are not added because I don't have test images

I could send you test image. Do you need it?

**Comment by diemmarkus** [comment]
yes, please! (ideally with different color formats)

**Comment by ZaWertun** [comment]
> yes, please! (ideally with different color formats)

It's photo taken from my mobile phone: http://zawertun.crabdance.com/20200620_175651.heic.

**Comment by jakar** [comment]
Merged without testing, because
- @ZaWertun already did confirm the fix for #17.
- I won't be able to switch around my work setup to do this until the weekend.

Thanks everyone!

**Comment by jakar** [comment]
Just reread your comments, and my merge might have been premature. Sorry if that's the case.

**Comment by diemmarkus** [comment]
> Just reread your comments, and my merge might have been premature. Sorry if that's the case

it should be fine. Only, if we have images stored in formats other than RGB and RGBA, we should come back to this...

**Pull request merged**
